import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Seed exercise_parameters for existing 15 exercises
 * Maps pedagogical metadata: year_level, tea_support, modalities, complexity
 */
export class SeedExerciseParameters1728000007000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // EF01MA03 Exercises (Comparison) - 12 exercises
    const ef01ma03Params = [
      {
        activity_id: 'ex-1-comparison-blocks',
        primary_skill: 'EF01MA03',
        secondary_skills: 'EF01MA06',
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 1,
        tea_support_min: 1,
        tea_support_max: 3,
        optimal_tea_support: 2,
        visual_intensity: 4.5,
        auditory_intensity: 1.5,
        kinesthetic_intensity: 4.0,
        complexity_score: 20,
        time_limit_seconds: 60,
        scaffolding_level: 'high',
        exercise_type: 'minigame',
        minigame_name: 'BlockStackingMinigame',
        engagement_score: 0.85,
        success_rate: 0.72,
      },
      {
        activity_id: 'ex-2-comparison-number-line',
        primary_skill: 'EF01MA03',
        secondary_skills: 'EF01MA08',
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 1,
        tea_support_min: 2,
        tea_support_max: 4,
        optimal_tea_support: 3,
        visual_intensity: 4.0,
        auditory_intensity: 2.0,
        kinesthetic_intensity: 3.5,
        complexity_score: 35,
        time_limit_seconds: 90,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'NumberLineMinigame',
        engagement_score: 0.80,
        success_rate: 0.68,
      },
      {
        activity_id: 'ex-3-matching-numbers',
        primary_skill: 'EF01MA03',
        secondary_skills: null,
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 1,
        tea_support_min: 1,
        tea_support_max: 3,
        optimal_tea_support: 2,
        visual_intensity: 4.0,
        auditory_intensity: 1.0,
        kinesthetic_intensity: 3.5,
        complexity_score: 25,
        time_limit_seconds: 75,
        scaffolding_level: 'high',
        exercise_type: 'minigame',
        minigame_name: 'MatchingMinigame',
        engagement_score: 0.78,
        success_rate: 0.70,
      },
      {
        activity_id: 'ex-4-stacking-game',
        primary_skill: 'EF01MA03',
        secondary_skills: 'EF01MA06',
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 1,
        tea_support_min: 2,
        tea_support_max: 4,
        optimal_tea_support: 2,
        visual_intensity: 4.5,
        auditory_intensity: 2.0,
        kinesthetic_intensity: 4.5,
        complexity_score: 30,
        time_limit_seconds: 120,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'BlockStackingMinigame',
        engagement_score: 0.90,
        success_rate: 0.75,
      },
      {
        activity_id: 'ex-5-number-line-advanced',
        primary_skill: 'EF01MA03',
        secondary_skills: 'EF01MA08',
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 2,
        tea_support_min: 2,
        tea_support_max: 4,
        optimal_tea_support: 3,
        visual_intensity: 4.0,
        auditory_intensity: 2.0,
        kinesthetic_intensity: 3.5,
        complexity_score: 45,
        time_limit_seconds: 100,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'NumberLineMinigame',
        engagement_score: 0.82,
        success_rate: 0.65,
      },
      {
        activity_id: 'ex-8-categorization-maior-menor',
        primary_skill: 'EF01MA03',
        secondary_skills: 'EF01MA14',
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 1,
        tea_support_min: 1,
        tea_support_max: 3,
        optimal_tea_support: 2,
        visual_intensity: 4.5,
        auditory_intensity: 1.5,
        kinesthetic_intensity: 3.5,
        complexity_score: 25,
        time_limit_seconds: 90,
        scaffolding_level: 'high',
        exercise_type: 'minigame',
        minigame_name: 'CategorizationMinigame',
        engagement_score: 0.84,
        success_rate: 0.71,
      },
      {
        activity_id: 'ex-6-ten-frame',
        primary_skill: 'EF01MA03',
        secondary_skills: 'EF01MA06',
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 1,
        tea_support_min: 1,
        tea_support_max: 3,
        optimal_tea_support: 2,
        visual_intensity: 4.0,
        auditory_intensity: 1.0,
        kinesthetic_intensity: 4.0,
        complexity_score: 30,
        time_limit_seconds: 75,
        scaffolding_level: 'high',
        exercise_type: 'minigame',
        minigame_name: 'TenFrameMinigame',
        engagement_score: 0.86,
        success_rate: 0.76,
      },
      {
        activity_id: 'ex-10-multi-select',
        primary_skill: 'EF01MA03',
        secondary_skills: null,
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 1,
        tea_support_min: 2,
        tea_support_max: 4,
        optimal_tea_support: 3,
        visual_intensity: 4.0,
        auditory_intensity: 2.0,
        kinesthetic_intensity: 4.0,
        complexity_score: 35,
        time_limit_seconds: 90,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'MultiSelectMinigame',
        engagement_score: 0.79,
        success_rate: 0.66,
      },
      {
        activity_id: 'ex-7-pattern-completion',
        primary_skill: 'EF01MA02',
        secondary_skills: 'EF01MA03',
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 1,
        tea_support_min: 2,
        tea_support_max: 4,
        optimal_tea_support: 3,
        visual_intensity: 3.5,
        auditory_intensity: 1.5,
        kinesthetic_intensity: 2.5,
        complexity_score: 40,
        time_limit_seconds: 120,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'PatternCompletionMinigame',
        engagement_score: 0.74,
        success_rate: 0.60,
      },
      {
        activity_id: 'ex-11-contextual-problem',
        primary_skill: 'EF01MA03',
        secondary_skills: null,
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 2,
        tea_support_min: 2,
        tea_support_max: 5,
        optimal_tea_support: 3,
        visual_intensity: 3.5,
        auditory_intensity: 3.0,
        kinesthetic_intensity: 2.5,
        complexity_score: 50,
        time_limit_seconds: 150,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'ContextualProblemMinigame',
        engagement_score: 0.81,
        success_rate: 0.62,
      },
      {
        activity_id: 'ex-12-true-false',
        primary_skill: 'EF01MA03',
        secondary_skills: null,
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 2,
        tea_support_min: 2,
        tea_support_max: 4,
        optimal_tea_support: 3,
        visual_intensity: 3.0,
        auditory_intensity: 2.5,
        kinesthetic_intensity: 3.0,
        complexity_score: 35,
        time_limit_seconds: 60,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'TrueFalseMinigame',
        engagement_score: 0.77,
        success_rate: 0.68,
      },
      {
        activity_id: 'ex-13-error-detection',
        primary_skill: 'EF01MA03',
        secondary_skills: null,
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 2,
        tea_support_min: 2,
        tea_support_max: 4,
        optimal_tea_support: 3,
        visual_intensity: 3.5,
        auditory_intensity: 3.0,
        kinesthetic_intensity: 2.5,
        complexity_score: 45,
        time_limit_seconds: 120,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'ErrorDetectionMinigame',
        engagement_score: 0.80,
        success_rate: 0.64,
      },
      {
        activity_id: 'ex-9-equation-builder',
        primary_skill: 'EF01MA03',
        secondary_skills: 'EF01MA06',
        target_year_min: 1,
        target_year_max: 2,
        optimal_year: 2,
        tea_support_min: 2,
        tea_support_max: 4,
        optimal_tea_support: 3,
        visual_intensity: 4.0,
        auditory_intensity: 1.5,
        kinesthetic_intensity: 3.5,
        complexity_score: 40,
        time_limit_seconds: 100,
        scaffolding_level: 'medium',
        exercise_type: 'minigame',
        minigame_name: 'EquationBuilderMinigame',
        engagement_score: 0.75,
        success_rate: 0.61,
      },
    ];

    // EF01MA04 Exercise
    const ef01ma04Params = {
      activity_id: 'ex-14-counting-100',
      primary_skill: 'EF01MA04',
      secondary_skills: 'EF01MA03',
      target_year_min: 2,
      target_year_max: 3,
      optimal_year: 2,
      tea_support_min: 2,
      tea_support_max: 4,
      optimal_tea_support: 2,
      visual_intensity: 4.5,
      auditory_intensity: 2.0,
      kinesthetic_intensity: 4.0,
      complexity_score: 55,
      time_limit_seconds: 180,
      scaffolding_level: 'medium',
      exercise_type: 'minigame',
      minigame_name: 'CountingCollectionMinigame',
      engagement_score: 0.82,
      success_rate: 0.65,
    };

    // EF01MA05 Exercise
    const ef01ma05Params = {
      activity_id: 'ex-15-ordering-two-digit',
      primary_skill: 'EF01MA05',
      secondary_skills: 'EF01MA03,EF01MA04',
      target_year_min: 2,
      target_year_max: 3,
      optimal_year: 2,
      tea_support_min: 2,
      tea_support_max: 4,
      optimal_tea_support: 3,
      visual_intensity: 4.0,
      auditory_intensity: 1.5,
      kinesthetic_intensity: 4.0,
      complexity_score: 50,
      time_limit_seconds: 120,
      scaffolding_level: 'medium',
      exercise_type: 'minigame',
      minigame_name: 'OrderingTwoDigitMinigame',
      engagement_score: 0.79,
      success_rate: 0.62,
    };

    // Insert all exercise parameters
    const allParams = [...ef01ma03Params, ef01ma04Params, ef01ma05Params];

    for (const param of allParams) {
      await queryRunner.query(
        `INSERT INTO exercise_parameters (
          activity_id, primary_skill, secondary_skills, target_year_min, target_year_max, 
          optimal_year, tea_support_min, tea_support_max, optimal_tea_support, 
          visual_intensity, auditory_intensity, kinesthetic_intensity, complexity_score, 
          time_limit_seconds, scaffolding_level, exercise_type, minigame_name, 
          engagement_score, success_rate, created_at, updated_at
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, NOW(), NOW())
        ON CONFLICT (activity_id) DO UPDATE SET 
          primary_skill = EXCLUDED.primary_skill,
          secondary_skills = EXCLUDED.secondary_skills,
          target_year_min = EXCLUDED.target_year_min,
          updated_at = NOW()`,
        [
          param.activity_id,
          param.primary_skill,
          param.secondary_skills,
          param.target_year_min,
          param.target_year_max,
          param.optimal_year,
          param.tea_support_min,
          param.tea_support_max,
          param.optimal_tea_support,
          param.visual_intensity,
          param.auditory_intensity,
          param.kinesthetic_intensity,
          param.complexity_score,
          param.time_limit_seconds,
          param.scaffolding_level,
          param.exercise_type,
          param.minigame_name,
          param.engagement_score,
          param.success_rate,
        ],
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DELETE FROM exercise_parameters WHERE activity_id LIKE \'ex-%\'');
  }
}
