import { DataSource } from 'typeorm';

export async function ActivitiesSeed(dataSource: DataSource) {
  const repo = dataSource.getRepository('activities');

  const activities = [
    // ── EF01MA01: Counting 1–10 ─────────────────────────────────────────
    {
      title: 'Conta as estrelas!',
      description: 'Conte os objetos e escolha o número certo',
      type: 'counting',
      difficulty: 'easy',
      bnccSkills: ['EF01MA01'],
      targetModalities: ['visual'],
      pointsReward: 10,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Quantas estrelas você vê?',
        instructions: 'How many stars do you see?',
        items: ['⭐','⭐','⭐'],
        options: [
          { id: 'a', text: '2', emoji: '2️⃣', isCorrect: false },
          { id: 'b', text: '3', emoji: '3️⃣', isCorrect: true },
          { id: 'c', text: '4', emoji: '4️⃣', isCorrect: false },
          { id: 'd', text: '5', emoji: '5️⃣', isCorrect: false },
        ],
        correctAnswer: '3',
      },
    },
    {
      title: 'Quantas maçãs?',
      description: 'Conte as frutas',
      type: 'counting',
      difficulty: 'easy',
      bnccSkills: ['EF01MA01'],
      targetModalities: ['visual'],
      pointsReward: 10,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Quantas maçãs há na cesta?',
        instructions: 'How many apples are in the basket?',
        items: ['🍎','🍎','🍎','🍎','🍎'],
        options: [
          { id: 'a', text: '3', emoji: '3️⃣', isCorrect: false },
          { id: 'b', text: '4', emoji: '4️⃣', isCorrect: false },
          { id: 'c', text: '5', emoji: '5️⃣', isCorrect: true },
          { id: 'd', text: '6', emoji: '6️⃣', isCorrect: false },
        ],
        correctAnswer: '5',
      },
    },
    // ── EF01MA03: Number comparison ─────────────────────────────────────
    {
      title: 'Qual número é maior?',
      description: 'Compare os números',
      type: 'quiz',
      difficulty: 'easy',
      bnccSkills: ['EF01MA03'],
      targetModalities: ['visual', 'logical'],
      pointsReward: 15,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Qual número é MAIOR: 7 ou 4?',
        instructions: 'Which number is BIGGER: 7 or 4?',
        options: [
          { id: 'a', text: '4', emoji: '4️⃣', isCorrect: false },
          { id: 'b', text: '7', emoji: '7️⃣', isCorrect: true },
          { id: 'c', text: 'São iguais', emoji: '🟰', isCorrect: false },
        ],
        correctAnswer: '7',
      },
    },
    {
      title: 'Menor ou maior?',
      description: 'Compare os números',
      type: 'quiz',
      difficulty: 'medium',
      bnccSkills: ['EF01MA03'],
      targetModalities: ['logical'],
      pointsReward: 20,
      isActive: true,
      accessibility: { sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Qual é o MENOR número: 15, 9 ou 12?',
        instructions: 'Which is the SMALLEST: 15, 9 or 12?',
        options: [
          { id: 'a', text: '15', isCorrect: false },
          { id: 'b', text: '12', isCorrect: false },
          { id: 'c', text: '9', isCorrect: true },
        ],
        correctAnswer: '9',
      },
    },
    // ── EF01MA06: Addition ───────────────────────────────────────────────
    {
      title: 'Sominha fácil!',
      description: 'Resolva a adição',
      type: 'quiz',
      difficulty: 'easy',
      bnccSkills: ['EF01MA06'],
      targetModalities: ['visual', 'logical'],
      pointsReward: 15,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: '🍬 + 🍬🍬 = ?',
        instructions: '1 candy + 2 candies = ?',
        items: ['🍬', '+', '🍬', '🍬', '=', '?'],
        options: [
          { id: 'a', text: '2', emoji: '2️⃣', isCorrect: false },
          { id: 'b', text: '3', emoji: '3️⃣', isCorrect: true },
          { id: 'c', text: '4', emoji: '4️⃣', isCorrect: false },
          { id: 'd', text: '1', emoji: '1️⃣', isCorrect: false },
        ],
        correctAnswer: '3',
      },
    },
    {
      title: '2 + 3 = ?',
      description: 'Adição com números',
      type: 'quiz',
      difficulty: 'easy',
      bnccSkills: ['EF01MA06'],
      targetModalities: ['logical'],
      pointsReward: 15,
      isActive: true,
      accessibility: { sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Quanto é 2 + 3?',
        instructions: 'What is 2 + 3?',
        options: [
          { id: 'a', text: '4', isCorrect: false },
          { id: 'b', text: '5', isCorrect: true },
          { id: 'c', text: '6', isCorrect: false },
          { id: 'd', text: '3', isCorrect: false },
        ],
        correctAnswer: '5',
      },
    },
    {
      title: 'Soma com bolas',
      description: 'Some as bolas coloridas',
      type: 'counting',
      difficulty: 'easy',
      bnccSkills: ['EF01MA06'],
      targetModalities: ['visual'],
      pointsReward: 15,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Some as bolas: 🔵🔵 + 🔴🔴🔴 = ?',
        instructions: 'Add the balls: 🔵🔵 + 🔴🔴🔴 = ?',
        items: ['🔵', '🔵', '+', '🔴', '🔴', '🔴'],
        options: [
          { id: 'a', text: '4', emoji: '4️⃣', isCorrect: false },
          { id: 'b', text: '5', emoji: '5️⃣', isCorrect: true },
          { id: 'c', text: '6', emoji: '6️⃣', isCorrect: false },
        ],
        correctAnswer: '5',
      },
    },
    // ── EF01MA07: Subtraction ────────────────────────────────────────────
    {
      title: 'Tirando biscoitos',
      description: 'Resolva a subtração',
      type: 'quiz',
      difficulty: 'easy',
      bnccSkills: ['EF01MA07'],
      targetModalities: ['visual'],
      pointsReward: 15,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Tinha 5 🍪, comeu 2. Quantos sobraram?',
        instructions: 'Had 5 🍪, ate 2. How many are left?',
        items: ['🍪','🍪','🍪','🍪','🍪'],
        options: [
          { id: 'a', text: '2', emoji: '2️⃣', isCorrect: false },
          { id: 'b', text: '3', emoji: '3️⃣', isCorrect: true },
          { id: 'c', text: '4', emoji: '4️⃣', isCorrect: false },
        ],
        correctAnswer: '3',
      },
    },
    {
      title: '8 - 3 = ?',
      description: 'Subtração',
      type: 'quiz',
      difficulty: 'medium',
      bnccSkills: ['EF01MA07'],
      targetModalities: ['logical'],
      pointsReward: 20,
      isActive: true,
      accessibility: { sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Quanto é 8 menos 3?',
        instructions: 'What is 8 minus 3?',
        options: [
          { id: 'a', text: '4', isCorrect: false },
          { id: 'b', text: '5', isCorrect: true },
          { id: 'c', text: '6', isCorrect: false },
          { id: 'd', text: '3', isCorrect: false },
        ],
        correctAnswer: '5',
      },
    },
    // ── EF02MA01: Numbers up to 100 ──────────────────────────────────────
    {
      title: 'Que número vem depois?',
      description: 'Sequência numérica',
      type: 'quiz',
      difficulty: 'medium',
      bnccSkills: ['EF02MA01'],
      targetModalities: ['logical'],
      pointsReward: 20,
      isActive: true,
      accessibility: { sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Que número vem depois de 29?',
        instructions: 'What number comes after 29?',
        options: [
          { id: 'a', text: '28', isCorrect: false },
          { id: 'b', text: '30', isCorrect: true },
          { id: 'c', text: '31', isCorrect: false },
          { id: 'd', text: '20', isCorrect: false },
        ],
        correctAnswer: '30',
      },
    },
    // ── EF02MA05: Doubling/Halving ───────────────────────────────────────
    {
      title: 'O dobro!',
      description: 'Calcule o dobro',
      type: 'quiz',
      difficulty: 'medium',
      bnccSkills: ['EF02MA05'],
      targetModalities: ['visual', 'logical'],
      pointsReward: 25,
      isActive: true,
      accessibility: { sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Qual é o dobro de 4?',
        instructions: 'What is double of 4?',
        options: [
          { id: 'a', text: '6', isCorrect: false },
          { id: 'b', text: '8', isCorrect: true },
          { id: 'c', text: '10', isCorrect: false },
          { id: 'd', text: '4', isCorrect: false },
        ],
        correctAnswer: '8',
      },
    },
    // ── EF03MA07: Multiplication ─────────────────────────────────────────
    {
      title: 'Tabuada do 2',
      description: 'Multiplicação por 2',
      type: 'quiz',
      difficulty: 'medium',
      bnccSkills: ['EF03MA07'],
      targetModalities: ['logical'],
      pointsReward: 25,
      isActive: true,
      accessibility: { sensoryLoad: 'low' },
      content: {
        instructionsPt: '3 × 2 = ?',
        instructions: '3 × 2 = ?',
        options: [
          { id: 'a', text: '5', isCorrect: false },
          { id: 'b', text: '6', isCorrect: true },
          { id: 'c', text: '8', isCorrect: false },
          { id: 'd', text: '4', isCorrect: false },
        ],
        correctAnswer: '6',
      },
    },
    {
      title: 'Tabuada do 5',
      description: 'Multiplicação por 5',
      type: 'quiz',
      difficulty: 'hard',
      bnccSkills: ['EF03MA07'],
      targetModalities: ['logical'],
      pointsReward: 30,
      isActive: true,
      accessibility: { sensoryLoad: 'medium' },
      content: {
        instructionsPt: '4 × 5 = ?',
        instructions: '4 × 5 = ?',
        options: [
          { id: 'a', text: '15', isCorrect: false },
          { id: 'b', text: '20', isCorrect: true },
          { id: 'c', text: '25', isCorrect: false },
          { id: 'd', text: '18', isCorrect: false },
        ],
        correctAnswer: '20',
      },
    },
    // ── DRAG-DROP: Ordering numbers ──────────────────────────────────────
    {
      title: 'Ordene do menor para o maior!',
      description: 'Arraste os números na ordem crescente',
      type: 'drag_drop',
      difficulty: 'easy',
      bnccSkills: ['EF01MA03'],
      targetModalities: ['visual', 'logical'],
      pointsReward: 20,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Arraste os números do MENOR para o MAIOR 👇',
        instructions: 'Drag the numbers from SMALLEST to BIGGEST',
        question: 'Coloque os números em ordem crescente: do menor para o maior!',
        items: [
          { id: 'n3', label: '3', emoji: '3️⃣' },
          { id: 'n1', label: '1', emoji: '1️⃣' },
          { id: 'n4', label: '4', emoji: '4️⃣' },
          { id: 'n2', label: '2', emoji: '2️⃣' },
        ],
        slotCount: 4,
        correctOrder: ['n1', 'n2', 'n3', 'n4'],
        correctAnswer: 'n1,n2,n3,n4',
      },
    },
    {
      title: 'Do maior para o menor!',
      description: 'Arraste os números em ordem decrescente',
      type: 'drag_drop',
      difficulty: 'medium',
      bnccSkills: ['EF01MA03'],
      targetModalities: ['visual', 'logical'],
      pointsReward: 25,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Arraste os números do MAIOR para o MENOR 👇',
        instructions: 'Drag the numbers from BIGGEST to SMALLEST',
        question: 'Coloque os números em ordem decrescente: do maior para o menor!',
        items: [
          { id: 'n7', label: '7', emoji: '7️⃣' },
          { id: 'n5', label: '5', emoji: '5️⃣' },
          { id: 'n9', label: '9', emoji: '9️⃣' },
          { id: 'n6', label: '6', emoji: '6️⃣' },
        ],
        slotCount: 4,
        correctOrder: ['n9', 'n7', 'n6', 'n5'],
        correctAnswer: 'n9,n7,n6,n5',
      },
    },
    {
      title: 'Complete a sequência!',
      description: 'Ordene os números que estão faltando',
      type: 'drag_drop',
      difficulty: 'easy',
      bnccSkills: ['EF02MA01'],
      targetModalities: ['visual', 'logical'],
      pointsReward: 20,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Complete a sequência: 10, ?, ?, 13',
        instructions: 'Complete the sequence: 10, ?, ?, 13',
        question: 'A sequência é 10, __, __, 13. Arraste os números que faltam na ordem certa!',
        items: [
          { id: 'n12', label: '12', emoji: '🔵' },
          { id: 'n11', label: '11', emoji: '🟡' },
        ],
        slotCount: 2,
        correctOrder: ['n11', 'n12'],
        correctAnswer: 'n11,n12',
      },
    },
    {
      title: 'Conta e ordena as frutas!',
      description: 'Ordene os grupos de frutas do menor para o maior',
      type: 'drag_drop',
      difficulty: 'easy',
      bnccSkills: ['EF01MA01'],
      targetModalities: ['visual'],
      pointsReward: 20,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Ordene os grupos do que tem MENOS para o que tem MAIS!',
        instructions: 'Order groups from FEWEST to MOST!',
        question: 'Arraste os grupos do que tem MENOS para o que tem MAIS frutas!',
        items: [
          { id: 'g3', label: '🍎🍎🍎', emoji: '' },
          { id: 'g1', label: '🍎', emoji: '' },
          { id: 'g2', label: '🍎🍎', emoji: '' },
        ],
        slotCount: 3,
        correctOrder: ['g1', 'g2', 'g3'],
        correctAnswer: 'g1,g2,g3',
      },
    },
    {
      title: 'Ordene os passos da adição!',
      description: 'Monte a conta de adição na ordem certa',
      type: 'drag_drop',
      difficulty: 'medium',
      bnccSkills: ['EF01MA06'],
      targetModalities: ['logical'],
      pointsReward: 25,
      isActive: true,
      accessibility: { sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Monte a conta: 4 + 3 = 7. Arraste na ordem!',
        instructions: 'Build the equation: 4 + 3 = 7. Drag in order!',
        question: 'Arraste as peças para montar a conta correta!',
        items: [
          { id: 'eq7', label: '7', emoji: '7️⃣' },
          { id: 'eqp', label: '+', emoji: '➕' },
          { id: 'eq4', label: '4', emoji: '4️⃣' },
          { id: 'eqe', label: '=', emoji: '🟰' },
          { id: 'eq3', label: '3', emoji: '3️⃣' },
        ],
        slotCount: 5,
        correctOrder: ['eq4', 'eqp', 'eq3', 'eqe', 'eq7'],
        correctAnswer: 'eq4,eqp,eq3,eqe,eq7',
      },
    },
    // ── EF01MA15: Shapes ─────────────────────────────────────────────────
    {
      title: 'Que forma é essa?',
      description: 'Reconheça as formas geométricas',
      type: 'quiz',
      difficulty: 'easy',
      bnccSkills: ['EF01MA15'],
      targetModalities: ['visual'],
      pointsReward: 15,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Como se chama essa forma? ⬜',
        instructions: 'What is this shape? ⬜',
        options: [
          { id: 'a', text: 'Círculo', emoji: '⭕', isCorrect: false },
          { id: 'b', text: 'Quadrado', emoji: '⬜', isCorrect: true },
          { id: 'c', text: 'Triângulo', emoji: '🔺', isCorrect: false },
          { id: 'd', text: 'Retângulo', emoji: '▬', isCorrect: false },
        ],
        correctAnswer: 'Quadrado',
      },
    },
    {
      title: 'Círculo ou quadrado?',
      description: 'Identifique a forma',
      type: 'quiz',
      difficulty: 'easy',
      bnccSkills: ['EF01MA15'],
      targetModalities: ['visual'],
      pointsReward: 15,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Uma pizza tem formato de... ⭕',
        instructions: 'A pizza has the shape of... ⭕',
        options: [
          { id: 'a', text: 'Quadrado', emoji: '⬜', isCorrect: false },
          { id: 'b', text: 'Círculo', emoji: '⭕', isCorrect: true },
          { id: 'c', text: 'Triângulo', emoji: '🔺', isCorrect: false },
        ],
        correctAnswer: 'Círculo',
      },
    },
    // ── PARAMETRIC FAMILIES: coverage-driven additions ─────────────────
    {
      title: 'Decomponha o número 7',
      description: 'Forme o todo a partir de duas partes',
      type: 'composition_decomposition',
      difficulty: 'easy',
      bnccSkills: ['EF01MA07'],
      targetModalities: ['visual', 'logical'],
      pointsReward: 20,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'O número 7 pode ser formado por 4 e quanto?',
        instructions: 'The number 7 can be composed of 4 and what number?',
        question: '7 = 4 + ?',
        pictogramConceptIds: ['math.whole', 'math.part'],
        options: [
          { id: 'part-2', text: '2', value: '2', isCorrect: false },
          { id: 'part-3', text: '3', value: '3', isCorrect: true },
          { id: 'part-4', text: '4', value: '4', isCorrect: false },
        ],
        correctAnswer: '3',
        validation: { kind: 'exact' },
        scaffolding: {
          hints: [
            { textLabel: 'Comece com 4 partes e conte até 7.', pictogramConceptId: 'math.part' },
          ],
          workedExample: '5 = 2 + 3',
          allowManipulatives: true,
        },
        semantic: {
          mathematicalConcepts: ['NumberConcept', 'AdditionConcept'],
          conceptMappingStatus: 'MAPPED',
          representation: ['object_based', 'pictorial', 'symbolic'],
          interactionType: ['composition_building'],
          difficultyProfile: {
            conceptualComplexity: null,
            numericalMagnitude: 7,
            abstractionLevel: null,
            stepCount: 2,
            distractorSimilarity: null,
            languageLoad: null,
            motorDemand: 'LOW',
            sensoryLoad: 'LOW',
            scaffoldingLevel: 'OPTIONAL',
          },
          affordances: {
            requiresDragging: false,
            requiresReading: true,
            usesAudio: false,
            usesPictograms: true,
          },
        },
      },
    },
    {
      title: 'Descubra o número que falta',
      description: 'Complete um fato básico da adição',
      type: 'missing_number',
      difficulty: 'easy',
      bnccSkills: ['EF01MA06'],
      targetModalities: ['logical'],
      pointsReward: 20,
      isActive: true,
      accessibility: { sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Qual número completa a igualdade?',
        instructions: 'Which number completes the equation?',
        question: '5 + ? = 8',
        inputMode: 'numeric',
        correctAnswer: 3,
        validation: { kind: 'numeric' },
        scaffolding: {
          hints: [{ textLabel: 'Conte do 5 até o 8.', pictogramConceptId: 'math.number_line' }],
          workedExample: '2 + ? = 5; o número que falta é 3.',
        },
        semantic: {
          mathematicalConcepts: ['AdditionConcept'],
          conceptMappingStatus: 'MAPPED',
          representation: ['symbolic'],
          interactionType: ['missing_value_entry'],
          difficultyProfile: {
            conceptualComplexity: null,
            numericalMagnitude: 8,
            abstractionLevel: null,
            stepCount: 1,
            distractorSimilarity: null,
            languageLoad: null,
            motorDemand: 'LOW',
            sensoryLoad: 'LOW',
            scaffoldingLevel: 'OPTIONAL',
          },
          affordances: {
            requiresDragging: false,
            requiresReading: true,
            usesAudio: false,
            usesPictograms: false,
          },
        },
      },
    },
    {
      title: 'Combine a forma com o nome',
      description: 'Relacione representações de uma figura plana',
      type: 'representation_matching',
      difficulty: 'easy',
      bnccSkills: ['EF01MA14'],
      targetModalities: ['visual'],
      pointsReward: 20,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Qual nome combina com esta forma?',
        instructions: 'Which name matches this shape?',
        question: '⬜',
        pictogramConceptIds: ['shape.square'],
        options: [
          { id: 'shape-circle', text: 'Círculo', value: 'circle', pictogramConceptId: 'shape.circle', isCorrect: false },
          { id: 'shape-square', text: 'Quadrado', value: 'square', pictogramConceptId: 'shape.square', isCorrect: true },
          { id: 'shape-triangle', text: 'Triângulo', value: 'triangle', pictogramConceptId: 'shape.triangle', isCorrect: false },
        ],
        correctAnswer: 'square',
        validation: { kind: 'exact' },
        scaffolding: {
          hints: [{ textLabel: 'Observe os quatro lados iguais.', pictogramConceptId: 'shape.square' }],
        },
        semantic: {
          mathematicalConcepts: ['BasicGeometryConcept', 'SquareConcept'],
          conceptMappingStatus: 'PARTIAL',
          representation: ['pictorial', 'object_based'],
          interactionType: ['representation_matching'],
          difficultyProfile: {
            conceptualComplexity: null,
            numericalMagnitude: null,
            abstractionLevel: null,
            stepCount: 1,
            distractorSimilarity: null,
            languageLoad: null,
            motorDemand: 'LOW',
            sensoryLoad: 'LOW',
            scaffoldingLevel: 'OPTIONAL',
          },
          affordances: {
            requiresDragging: false,
            requiresReading: true,
            usesAudio: false,
            usesPictograms: true,
          },
        },
      },
    },
    {
      title: 'A conta da TitiA está certa?',
      description: 'Avalie uma afirmação e escolha uma justificativa',
      type: 'error_detection',
      difficulty: 'medium',
      bnccSkills: ['EF01MA06'],
      targetModalities: ['logical'],
      pointsReward: 25,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'TitiA pensa que 3 + 2 = 6. Ela está certa? Escolha também o motivo.',
        instructions: 'TitiA thinks 3 + 2 = 6. Is she right? Also choose the reason.',
        question: '3 + 2 = 6?',
        pictogramConceptIds: ['character.titia'],
        options: [
          { id: 'verdict-yes', text: 'Sim', value: true, pictogramConceptId: 'action.yes', isCorrect: false },
          { id: 'verdict-no', text: 'Não', value: false, pictogramConceptId: 'action.no', isCorrect: true },
        ],
        reasonOptions: [
          { id: 'reason-five', text: 'Porque 3 + 2 = 5', value: 'sum_is_five', isCorrect: true },
          { id: 'reason-six', text: 'Porque 3 + 2 = 6', value: 'sum_is_six', isCorrect: false },
        ],
        correctAnswer: { value: false, reason: 'sum_is_five' },
        validation: { kind: 'compound' },
        scaffolding: {
          hints: [{ textLabel: 'Conte três objetos e depois mais dois.', pictogramConceptId: 'math.addition' }],
          requireReason: true,
        },
        semantic: {
          mathematicalConcepts: ['AdditionConcept'],
          conceptMappingStatus: 'MAPPED',
          representation: ['contextual', 'symbolic', 'pictorial'],
          interactionType: ['error_evaluation'],
          difficultyProfile: {
            conceptualComplexity: null,
            numericalMagnitude: 6,
            abstractionLevel: null,
            stepCount: 2,
            distractorSimilarity: null,
            languageLoad: null,
            motorDemand: 'LOW',
            sensoryLoad: 'LOW',
            scaffoldingLevel: 'OPTIONAL',
          },
          affordances: {
            requiresDragging: false,
            requiresReading: true,
            usesAudio: false,
            usesPictograms: true,
          },
        },
      },
    },
    {
      title: 'Maçãs para o lanche',
      description: 'Resolva uma situação de juntar quantidades',
      type: 'contextual_problem_solving',
      difficulty: 'easy',
      bnccSkills: ['EF01MA08'],
      targetModalities: ['visual', 'logical'],
      pointsReward: 25,
      isActive: true,
      accessibility: { hasVisual: true, sensoryLoad: 'low' },
      content: {
        instructionsPt: 'Havia 3 maçãs. Colocaram mais 2. Quantas maçãs há agora?',
        instructions: 'There were 3 apples. Two more were added. How many are there now?',
        question: '🍎🍎🍎 + 🍎🍎 = ?',
        context: { operationMeaning: 'join' },
        pictogramConceptIds: ['object.apple', 'math.addition'],
        inputMode: 'numeric',
        correctAnswer: 5,
        validation: { kind: 'numeric' },
        scaffolding: {
          hints: [{ textLabel: 'Junte os dois grupos de maçãs e conte.', pictogramConceptId: 'object.apple' }],
          allowManipulatives: true,
        },
        semantic: {
          mathematicalConcepts: ['AdditionConcept', 'EarlyProblemSolvingConcept'],
          conceptMappingStatus: 'PARTIAL',
          representation: ['contextual', 'object_based', 'pictorial'],
          interactionType: ['contextual_response'],
          difficultyProfile: {
            conceptualComplexity: null,
            numericalMagnitude: 5,
            abstractionLevel: null,
            stepCount: 2,
            distractorSimilarity: null,
            languageLoad: null,
            motorDemand: 'LOW',
            sensoryLoad: 'LOW',
            scaffoldingLevel: 'OPTIONAL',
          },
          affordances: {
            requiresDragging: false,
            requiresReading: true,
            usesAudio: false,
            usesPictograms: true,
          },
        },
      },
    },
  ];

  const existingRecords = await repo.find({ select: ['title'] });
  const existingTitles = new Set(existingRecords.map((record: any) => record.title));
  let created = 0;
  for (const activity of activities) {
    if (existingTitles.has(activity.title)) continue;
    const record = repo.create(activity);
    await repo.save(record);
    created += 1;
  }

  console.log(`✅ ${created} new activities seeded (${activities.length} defined)`);
}
